services:
  db:
    image: postgres:16-alpine
    container_name: drogueria_pilar_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: drogueria_pilar
      POSTGRES_USER: pilar_user
      POSTGRES_PASSWORD: pilar_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
